import type { ActivityEntry, DepartmentNode, ProcessRecord } from '../types'

const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString()

export const seedProcesses: ProcessRecord[] = [
  {
    id: 'proc-onboarding',
    title: 'Flujo de incorporación de clientes',
    summary:
      'Automatiza la recolección de documentación y los pasos de verificación legal, reduciendo el tiempo de activación en un 40%.',
    status: 'Published',
    category: 'Ventas',
    area: 'Ventas',
    impactHoursPerWeek: 6,
    impactNote: 'Reduce el tiempo de activación de nuevos clientes de 3 días a menos de 1.',
    tags: ['Onboarding', 'CRM'],
    owner: 'Equipo de Ventas',
    createdAt: daysAgo(120),
    updatedAt: daysAgo(3),
    steps: [
      { id: 's1', title: 'Recolectar documentos del cliente', description: 'Solicita y valida la documentación de incorporación mediante el portal.', done: true },
      { id: 's2', title: 'Validar información en el CRM', description: 'Confirma que los datos del cliente estén completos antes de activar la cuenta.', done: true },
      { id: 's3', title: 'Activar cuenta y enviar bienvenida', description: 'Provisiona el acceso y envía la secuencia de bienvenida.', done: true },
    ],
    contributors: [{ id: 'c1', name: 'Jordan S.', role: 'Líder de Ventas' }],
    timeToExecute: '20m',
    complexity: 'Medium',
    efficiencyScore: 88,
    sourceType: 'manual',
  },
  {
    id: 'proc-leadgen',
    title: 'Generación y calificación de leads',
    summary: 'Proceso para captar leads desde campañas digitales y calificarlos antes de pasarlos a ventas.',
    status: 'Published',
    category: 'Marketing',
    area: 'Marketing',
    impactHoursPerWeek: 5,
    impactNote: 'Reduce el costo por lead calificado en ~22% al filtrar antes de pasar a ventas.',
    tags: ['Campañas', 'Leads'],
    owner: 'Equipo de Marketing',
    createdAt: daysAgo(80),
    updatedAt: daysAgo(4),
    steps: [
      { id: 's1', title: 'Publicar campaña en redes', description: 'Programa el contenido y presupuesto de la campaña activa.', done: true },
      { id: 's2', title: 'Calificar leads entrantes', description: 'Aplica el checklist de calificación (presupuesto, necesidad, urgencia).', done: false },
      { id: 's3', title: 'Enviar leads calificados a ventas', description: 'Transfiere solo los leads que cumplen el criterio mínimo al CRM de ventas.', done: false },
    ],
    contributors: [{ id: 'c5', name: 'Marta G.', role: 'Marketing Digital' }],
    timeToExecute: '1h',
    complexity: 'Medium',
    efficiencyScore: 71,
    sourceType: 'manual',
  },
  {
    id: 'proc-cloud-scaling',
    title: 'Escalado de recursos en la nube',
    summary: 'Guía técnica para el escalado de servidores. Marcado para revisión por referencias a configuraciones obsoletas.',
    status: 'Needs Review',
    category: 'Operaciones',
    area: 'Operaciones',
    impactHoursPerWeek: 2,
    impactNote: 'Evita caídas de servicio que hoy cuestan horas de soporte no planeadas.',
    tags: ['Infraestructura', 'DevOps'],
    createdAt: daysAgo(60),
    updatedAt: daysAgo(1),
    steps: [
      { id: 's1', title: 'Auditar carga de servidores actual', description: 'Revisa el uso de recursos y detecta cuellos de botella.', done: false },
      { id: 's2', title: 'Actualizar política de escalado', description: 'Ajusta los límites automáticos según la demanda real.', done: false },
    ],
    contributors: [{ id: 'c2', name: 'Alex Lewis', role: 'Ingeniero de Operaciones' }],
    timeToExecute: '1h',
    complexity: 'Medium',
    efficiencyScore: 63,
    sourceType: 'manual',
  },
  {
    id: 'proc-security-patching',
    title: 'Parcheo de seguridad mensual',
    summary: 'Protocolo mensual para aplicar actualizaciones de seguridad a servidores de producción sin afectar el servicio.',
    status: 'Published',
    category: 'Operaciones',
    area: 'Operaciones',
    impactHoursPerWeek: 3,
    impactNote: 'Reduce incidentes de seguridad y el tiempo de respuesta ante vulnerabilidades.',
    tags: ['Seguridad', 'Mantenimiento'],
    owner: 'Equipo de Operaciones',
    createdAt: daysAgo(340),
    updatedAt: daysAgo(45),
    steps: [
      {
        id: 's1',
        title: 'Respaldo previo a la actualización',
        description: 'Genera un respaldo de todos los volúmenes de producción antes de iniciar cualquier cambio.',
        done: false,
      },
      {
        id: 's2',
        title: 'Aplicar parches de seguridad',
        description: 'Actualiza el sistema y verifica que los parches críticos se apliquen correctamente.',
        done: false,
        priority: 'High',
        assignee: 'Equipo de Operaciones',
      },
      {
        id: 's3',
        title: 'Revisar reglas de acceso',
        description: 'Confirma que solo los accesos autorizados sigan activos tras la actualización.',
        done: false,
      },
    ],
    contributors: [
      { id: 'c2', name: 'Alex Lewis', role: 'Ingeniero de Operaciones' },
      { id: 'c3', name: 'Sam Rivers', role: 'Seguridad' },
    ],
    timeToExecute: '45m',
    complexity: 'High',
    efficiencyScore: 94,
    sourceType: 'voice',
    transcript: [
      { id: 't1', speaker: 'user', text: 'Nota de voz del 24/10/2023 detallando el parcheo mensual de seguridad de servidores.', timestamp: daysAgo(45) },
    ],
    aiSuggestions: ['Verificar vencimiento de certificado SSL', 'Actualizar manifiesto de acceso del equipo'],
  },
  {
    id: 'proc-cierre-mensual',
    title: 'Cierre contable mensual',
    summary: 'Checklist para conciliar cuentas, generar reportes y cerrar el mes contable sin retrasos.',
    status: 'Draft',
    category: 'Finanzas',
    area: 'Finanzas',
    impactHoursPerWeek: 4,
    impactNote: 'Acorta el cierre mensual de 5 días a 3, liberando tiempo del equipo contable.',
    tags: ['Contabilidad', 'Reportes'],
    createdAt: daysAgo(90),
    updatedAt: daysAgo(6),
    steps: [
      { id: 's1', title: 'Conciliar cuentas bancarias', description: 'Compara los movimientos bancarios contra el registro contable.', done: false },
      { id: 's2', title: 'Revisar cuentas por cobrar y pagar', description: 'Verifica el estado de facturas pendientes antes del cierre.', done: false },
      { id: 's3', title: 'Generar reporte financiero mensual', description: 'Consolida los resultados y comparte el reporte con dirección.', done: false },
    ],
    contributors: [{ id: 'c6', name: 'Diego R.', role: 'Contador' }],
    timeToExecute: '2h',
    complexity: 'High',
    efficiencyScore: 41,
    sourceType: 'manual',
  },
]

export const seedDepartments: DepartmentNode[] = [
  {
    id: 'dept-ventas',
    name: 'Ventas',
    description: 'Rutas de venta, seguimiento de leads calificados y cierres.',
    icon: 'Ventas',
    completeness: 82,
    roiMetric: 'Horas ahorradas / semana',
    roiValue: '6h',
  },
  {
    id: 'dept-marketing',
    name: 'Marketing',
    description: 'Campañas, generación de leads y contenido.',
    icon: 'Marketing',
    completeness: 55,
    roiMetric: 'Costo por lead reducido',
    roiValue: '-22%',
  },
  {
    id: 'dept-operaciones',
    name: 'Operaciones',
    description: 'Procesos internos, infraestructura y mantenimiento.',
    icon: 'Operaciones',
    completeness: 64,
    roiMetric: 'Horas ahorradas / semana',
    roiValue: '5h',
  },
  {
    id: 'dept-finanzas',
    name: 'Finanzas',
    description: 'Cierre contable, cobros y reportes financieros.',
    icon: 'Finanzas',
    completeness: 38,
    roiMetric: 'Horas ahorradas / semana',
    roiValue: '4h',
  },
]

export const seedActivity: ActivityEntry[] = [
  { id: 'a1', text: 'Agent Brain completó la documentación de "Generación y calificación de leads" (Marketing).', timestamp: daysAgo(0) },
  { id: 'a2', text: 'Jordan S. revisó el SOP de incorporación de clientes (Ventas).', timestamp: daysAgo(0) },
  { id: 'a3', text: 'Agent Brain detectó un vacío en el proceso de escalado de recursos (Operaciones).', timestamp: daysAgo(0) },
  { id: 'a4', text: 'El sistema actualizó automáticamente el checklist de cierre contable (Finanzas).', timestamp: daysAgo(1) },
]
